# (c) Copyright 2018 Hewlett Packard Enterprise Development LP

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

# http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: Pod
metadata:
  labels:
    app: hr
    env: stage
    tier: database
  name: hr-stage-database-5
  namespace: ep2
spec:
  containers:
  - env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: database-passwd
          key: pass
    - name: MYSQL_DATABASE
      valueFrom:
        configMapKeyRef:
          name: database-config
          key: dbname
    image: mysql:5.6
    name: mysql
    ports:
    - containerPort: 3306
      name: mysql
      protocol: TCP
    volumeMounts:
    - mountPath: /etc/mysql/conf.d
      name: tuning-conf
    - mountPath: /var/lib/mysql
      name: mysql-persistent-storage
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  volumes:
  - name: tuning-conf
    configMap:
      name: database-tune
  - name: mysql-persistent-storage
    flexVolume:
     driver: hpe.com/nimble
     options:
      sizeInGiB: "30"
      dedupe: "true"
      name: "example-storage-volume"
      description: "Stage hr database"
      perfPolicy: "SQL Server"
      protectionTemplate: "Retain-48Hourly-30Daily-52Weekly"
      thick: "false"
      mountConflictDelay: "30"